# Generated by Django 5.1.4 on 2025-01-07 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='email',
            field=models.EmailField(default='exit', max_length=255),
            preserve_default=False,
        ),
    ]
