# Generated by Django 5.1.4 on 2025-01-09 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_application_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='promotion',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='activity_photos/'),
        ),
    ]
