# Generated by Django 5.1.4 on 2025-01-09 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_promotion_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='promotion_photos/'),
        ),
    ]
