# Generated by Django 5.1.4 on 2025-01-09 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_alter_activity_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('text', models.TextField()),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='testimonial_pictures/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
