# Generated by Django 5.1.4 on 2025-01-10 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_testimonial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='promotion',
            old_name='photo',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='teammember',
            old_name='photo',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='testimonial',
            old_name='profile_picture',
            new_name='image',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='photo',
        ),
        migrations.AddField(
            model_name='activity',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='promotion_photos/'),
        ),
    ]
