# Generated by Django 5.1.4 on 2025-01-13 07:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0008_alter_service_name_alter_subservice_frequence_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credit',
            name='frequence',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='credit',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='credit',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credit', to='services.service'),
        ),
        migrations.AlterField(
            model_name='credit',
            name='taux',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='service',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='subservice',
            name='frequence',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='subservice',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='subservice',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subservices', to='services.service'),
        ),
        migrations.AlterField(
            model_name='subservice',
            name='taux',
            field=models.CharField(max_length=100),
        ),
    ]
